apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nova-compute-default
spec:
  template:
    spec:
      containers:
      - name: nova-compute-default
        volumeMounts:
        - mountPath: /etc/nova/nova.conf
          name: nsx-nova-etc
          readOnly: true
          subPath: nova-compute.conf
      volumes:
      - name: nsx-nova-etc
        secret:
          defaultMode: 292
          secretName: nsx-nova-etc
      initContainers:
      - name: init
        env:
        - name: DEPENDENCY_POD_JSON
          value: '[{"labels":{"application":"libvirt","component":"libvirt"},"requireSameNode":true}]'